# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]
highlighter:         pygments

# Permalinks
permalink:        pretty

# Setup
title:            Mark Stoehr
tagline:          'Speech Recognition, Data Science, Deep Learning'
description:      'A personal web-page for organizing my work and projects'
url:              http://markstoehr.com
baseurl:          '/'
paginate:         5

author:
  name:           'Mark Stoehr'


# Custom vars
version:          1.0.0

github:
  repo: github.com/joshualande/joshualande.github.io
